### ISSUE TITLE
iOS Jailbreaks

### ISSUE THREAD

**Issue by MrAct1on** [crispy78/FindMy#1]
Where did u go to get & install the jailbreak software? I’ve tried countless google searches to find a legit site and haven’t found anything. Can u plz share? Thx

**Comment by DutchCoban** [comment]
https://github.com/palera1n/palen1x download the .ISO from https://github.com/palera1n/palen1x/releases and follow the instructions as mentioned on https://ios.cfw.guide/using-palen1x/

**Comment by crispy78** [comment]
I think this "issue" has been solved :-)

**Comment by DutchCoban** [comment]
The issue has been solved
